const $=s=>document.querySelector(s);
const boardEl=$('#board'),statusEl=$('#status'),turnEl=$('#turn'),scoreXEl=$('#scoreX'),scoreOEl=$('#scoreO'),scoreXLabel=$('#scoreXLabel'),scoreOLabel=$('#scoreOLabel');
const difficultyEl=$('#difficulty'),difficultyWrap=$('#difficultyWrap'),markWrap=$('#markWrap'),playerMarkEl=$('#playerMark'),matchLengthEl=$('#matchLength'),starterEl=$('#starter'),timeLimitEl=$('#timeLimit');
const soundToggle=$('#soundToggle'),gamesPlayedEl=$('#gamesPlayed'),gamesWonEl=$('#gamesWon'),gamesLostEl=$('#gamesLost'),gamesDrawEl=$('#gamesDraw'),winStreakEl=$('#winStreak');
const progressFill=$('#progressFill'),matchInfoEl=$('#matchInfo'),roundInfoEl=$('#roundInfo'),timerValueEl=$('#timerValue'),timerFillEl=$('#timerFill'),undoBtn=$('#undo'),hintBtn=$('#hintBtn'),surrenderBtn=$('#surrenderBtn');
const achievementFirst=$('#achievementFirst'),achievementStreak=$('#achievementStreak'),achievementPerfect=$('#achievementPerfect');
const modeButtons=[...document.querySelectorAll('.mode')],resultModal=$('#resultModal'),resultIcon=$('#resultIcon'),resultTitle=$('#resultTitle'),resultText=$('#resultText'),resultScore=$('#resultScore'),nextRoundBtn=$('#nextRound'),closeResultBtn=$('#closeResult');
const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],corners=[0,2,6,8],empty=()=>Array(9).fill('');
let board=empty(),current='X',gameOver=false,thinking=false,mode=localStorage.getItem('tttMode')||'ai',human=localStorage.getItem('tttHuman')||'X',ai='O';
let soundOn=localStorage.getItem('tttSound')!=='off',score={X:+localStorage.getItem('tttX')||0,O:+localStorage.getItem('tttO')||0};
let stats={games:+localStorage.getItem('tttGames')||0,wins:+localStorage.getItem('tttWins')||0,losses:+localStorage.getItem('tttLosses')||0,draws:+localStorage.getItem('tttDraws')||0,streak:+localStorage.getItem('tttStreak')||0,perfect:+localStorage.getItem('tttPerfect')||0};
let matchScores={X:0,O:0},round=0,history=[],aiTimer=null,audioContext=null,matchFinished=false,hintUsed=false,hintTimer=null,turnTimer=null,timerStartedAt=0,timeLeft=0;
function targetWins(){return +matchLengthEl.value} function limit(){return +timeLimitEl.value} function isAiTurn(){return mode==='ai'&&current===ai&&!gameOver&&!matchFinished}
function playerLabel(s){return mode==='local'?(s==='X'?'Крестики':'Нолики'):(s===human?'Вы':'ИИ')}
function getWinner(state){for(const line of wins){const[a,b,c]=line;if(state[a]&&state[a]===state[b]&&state[a]===state[c])return line}return null}
function isDraw(state){return state.every(Boolean)&&!getWinner(state)}
function save(){for(const[k,v]of Object.entries({tttX:score.X,tttO:score.O,tttGames:stats.games,tttWins:stats.wins,tttLosses:stats.losses,tttDraws:stats.draws,tttStreak:stats.streak,tttPerfect:stats.perfect,tttSound:soundOn?'on':'off',tttMode:mode,tttHuman:human,tttDifficulty:difficultyEl.value,tttMatchLength:matchLengthEl.value,tttStarter:starterEl.value,tttTimeLimit:timeLimitEl.value}))localStorage.setItem(k,v)}
function updateStats(){gamesPlayedEl.textContent=stats.games;gamesWonEl.textContent=stats.wins;gamesLostEl.textContent=stats.losses;gamesDrawEl.textContent=stats.draws;winStreakEl.textContent=stats.streak;achievementFirst.classList.toggle('unlocked',stats.wins>0);achievementStreak.classList.toggle('unlocked',stats.streak>=3);achievementPerfect.classList.toggle('unlocked',stats.perfect>0)}
function updateMatch(){const t=targetWins(),leader=Math.max(matchScores.X,matchScores.O);matchInfoEl.textContent=t===1?'До 1 победы':`Матч до ${t} побед`;roundInfoEl.textContent=`Раунд ${round}`;progressFill.style.width=matchFinished?'100%':`${Math.min(100,leader/t*100)}%`;undoBtn.disabled=history.length===0||thinking||gameOver||matchFinished;hintBtn.disabled=mode!=='ai'||current!==human||gameOver||thinking||matchFinished||hintUsed;surrenderBtn.disabled=mode!=='ai'||gameOver||thinking||matchFinished}
function render(winLine=null){boardEl.innerHTML='';board.forEach((v,i)=>{const c=document.createElement('button');c.type='button';c.className=`cell${v?' '+v.toLowerCase():''}${winLine?.includes(i)?' win':''}`;c.textContent=v;c.disabled=Boolean(v)||gameOver||thinking||matchFinished;c.setAttribute('aria-label',`Клетка ${i+1}${v?', '+playerLabel(v):''}`);c.addEventListener('click',()=>move(i));boardEl.appendChild(c)});scoreXEl.textContent=score.X;scoreOEl.textContent=score.O;scoreXLabel.textContent=playerLabel('X');scoreOLabel.textContent=playerLabel('O');turnEl.textContent=matchFinished?'Матч завершён':gameOver?'Раунд завершён':mode==='ai'?(current===human?'Ваш ход':'Ход ИИ…'):`Ход ${playerLabel(current)}`;soundToggle.textContent=soundOn?'🔊':'🔇';updateStats();updateMatch();updateTimerUI()}
function updateTimerUI(){if(!limit()){timerValueEl.textContent='—';timerFillEl.style.width='100%';return}timerValueEl.textContent=`${Math.max(0,timeLeft)}с`;timerFillEl.style.width=`${Math.max(0,Math.min(100,timeLeft/limit()*100))}%`}
function stopTurnTimer(){if(turnTimer){clearInterval(turnTimer);turnTimer=null}}
function startTurnTimer(){stopTurnTimer();if(!limit()||gameOver||matchFinished)return;timeLeft=limit();timerStartedAt=performance.now();updateTimerUI();turnTimer=setInterval(()=>{const elapsed=Math.floor((performance.now()-timerStartedAt)/1000);timeLeft=limit()-elapsed;updateTimerUI();if(timeLeft<=0){stopTurnTimer();timeExpired()}},100)}
function timeExpired(){if(gameOver||matchFinished)return;if(mode==='ai'&&current===human){statusEl.textContent='Время вышло — раунд получает ИИ.';finishByTimeout(ai)}else if(mode==='local'){const winner=current==='X'?'O':'X';statusEl.textContent='Время вышло — ход передан сопернику.';finishByTimeout(winner)}else finishByTimeout(ai)}
function finishByTimeout(winner){gameOver=true;const old=current;current=winner;score[winner]++;matchScores[winner]++;stats.games++;if(mode==='ai'){if(winner===human){stats.wins++;stats.streak++}else{stats.losses++;stats.streak=0}}else{if(winner==='X')stats.wins++;else stats.losses++}save();beep(winner===human?660:180,.2,'sawtooth');render();setTimeout(()=>showResult(winner===human?'Вы выиграли по времени!':'Время вышло',`Счёт матча: ${matchScores[human]??matchScores.X} : ${matchScores[ai]??matchScores.O}`,winner===human?'⏱️':'⌛'),350);current=old}
function beep(freq=440,d=.07,type='sine'){if(!soundOn)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.06,audioContext.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+d);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+d+.02)}catch{}}
function showResult(title,text,icon='🏆'){resultIcon.textContent=icon;resultTitle.textContent=title;resultText.textContent=text;resultScore.textContent=mode==='local'?`${matchScores.X} : ${matchScores.O}`:`${matchScores[human]} : ${matchScores[ai]}`;resultModal.hidden=false;nextRoundBtn.textContent=matchFinished?'Новый матч':'Следующий раунд';nextRoundBtn.focus()}
function hideResult(){resultModal.hidden=true}
function finish(line){stopTurnTimer();gameOver=true;const winner=board[line[0]];score[winner]++;matchScores[winner]++;stats.games++;if(mode==='ai'){if(winner===human){stats.wins++;stats.streak++;if(difficultyEl.value==='hard'&&!hintUsed)stats.perfect++}else{stats.losses++;stats.streak=0}}else{winner==='X'?stats.wins++:stats.losses++}save();statusEl.textContent=mode==='ai'?(winner===human?'Вы забрали раунд! 🎉':'ИИ забрал раунд.'):`Раунд выиграли ${playerLabel(winner)}!`;beep(winner===human?660:220,.18,'triangle');render(line);if(matchScores[winner]>=targetWins()){matchFinished=true;setTimeout(()=>{render(line);showResult(winner===human?'Вы выиграли матч!':'Матч выиграл ИИ',winner===human?'Отличная победная серия.':'Попробуйте другую тактику.',winner===human?'🏆':'🤖');beep(winner===human?880:160,.25,'sawtooth')},500)}else setTimeout(()=>showResult(winner===human?'Раунд за вами!':'Раунд за ИИ',`Счёт матча: ${matchScores[human]} : ${matchScores[ai]}`,winner===human?'🎉':'🤖'),350)}
function finishDraw(){stopTurnTimer();gameOver=true;stats.games++;stats.draws++;if(mode==='ai')stats.streak=0;save();statusEl.textContent='Ничья. Раунд без победителя.';beep(330,.15,'square');render();setTimeout(()=>showResult('Ничья','Никто не забрал раунд.','🤝'),350)}
function startRound(){if(aiTimer){clearTimeout(aiTimer);aiTimer=null}if(hintTimer){clearTimeout(hintTimer);hintTimer=null}stopTurnTimer();hideResult();board=empty();thinking=false;gameOver=false;history=[];hintUsed=false;round++;const starter=starterEl.value;current=starter==='random'?(Math.random()<.5?'X':'O'):'X';statusEl.textContent=mode==='ai'?(current===human?'Ваш ход — выберите клетку':'ИИ начинает…'):`Ход ${playerLabel(current)}`;render();startTurnTimer();if(isAiTurn()){thinking=true;render();aiTimer=setTimeout(aiMove,420)}}
function newMatch(){if(aiTimer){clearTimeout(aiTimer);aiTimer=null}matchScores={X:0,O:0};round=0;matchFinished=false;startRound()}
function move(i){if(gameOver||thinking||matchFinished||board[i]||isAiTurn())return;if(hintTimer){clearTimeout(hintTimer);hintTimer=null}history.push({board:[...board],current});board[i]=current;beep(current===human?520:360);const line=getWinner(board);if(line){render(line);return finish(line)}if(isDraw(board))return finishDraw();current=current==='X'?'O':'X';statusEl.textContent=mode==='ai'?'ИИ думает…':`Ход ${playerLabel(current)}`;render();startTurnTimer();if(isAiTurn()){thinking=true;render();aiTimer=setTimeout(aiMove,360)}}
function findImmediateMove(state,player){for(let i=0;i<9;i++)if(!state[i]){state[i]=player;const ok=!!getWinner(state);state[i]='';if(ok)return i}return null}
function randomMove(state){const free=state.map((v,i)=>v?null:i).filter(v=>v!==null);return free.length?free[Math.floor(Math.random()*free.length)]:null}
function chooseEasy(state){return randomMove(state)}
function chooseMedium(state){const win=findImmediateMove(state,ai);if(win!==null)return win;const block=findImmediateMove(state,human);if(block!==null)return block;if(!state[4])return 4;const cs=corners.filter(i=>!state[i]);return cs.length?cs[Math.floor(Math.random()*cs.length)]:randomMove(state)}
function minimax(state,maximizing,depth=0){const line=getWinner(state);if(line)return{score:state[line[0]]===ai?10-depth:depth-10};if(state.every(Boolean))return{score:0};const moves=[];for(let i=0;i<9;i++){if(state[i])continue;state[i]=maximizing?ai:human;moves.push({index:i,score:minimax(state,!maximizing,depth+1).score});state[i]=''};return maximizing?moves.reduce((a,b)=>b.score>a.score?b:a):moves.reduce((a,b)=>b.score<a.score?b:a)}
function chooseHard(state){return minimax([...state],true).index}
function chooseAiMove(){return difficultyEl.value==='easy'?chooseEasy(board):difficultyEl.value==='hard'?chooseHard(board):chooseMedium(board)}
function aiMove(){aiTimer=null;if(!isAiTurn()){thinking=false;render();return}const i=chooseAiMove();thinking=false;if(i===null){render();return}history.push({board:[...board],current});board[i]=ai;beep(ai===human?520:360);const line=getWinner(board);if(line)return finish(line);if(isDraw(board))return finishDraw();current=human;statusEl.textContent='Ваш ход — выберите клетку';render();startTurnTimer()}
function undo(){if(thinking||gameOver||matchFinished||!history.length)return;if(aiTimer){clearTimeout(aiTimer);aiTimer=null;thinking=false}if(hintTimer){clearTimeout(hintTimer);hintTimer=null}const previous=history.pop();board=previous.board;current=previous.current;if(mode==='ai'&&previous.current===ai&&history.length){const second=history.pop();board=second.board;current=second.current}statusEl.textContent=mode==='ai'?'Ход отменён — ваш ход.':`Ход ${playerLabel(current)}`;beep(240,.06);render();startTurnTimer()}
function chooseBestHint(state,player){const win=findImmediateMove(state,player);if(win!==null)return win;const opp=player==='X'?'O':'X',block=findImmediateMove(state,opp);if(block!==null)return block;if(!state[4])return 4;const cs=corners.filter(i=>!state[i]);return cs.length?cs[0]:randomMove(state)}
function giveHint(){if(hintBtn.disabled)return;const i=chooseBestHint(board,current);if(i===null)return;hintUsed=true;statusEl.textContent=`Подсказка: попробуйте клетку ${i+1}`;render();boardEl.children[i]?.classList.add('hint');beep(740,.08);hintTimer=setTimeout(()=>{boardEl.children[i]?.classList.remove('hint');hintTimer=null;if(!gameOver&&!thinking)statusEl.textContent=current===human?'Ваш ход — выберите клетку':'Ход соперника'},1500)}
function surrender(){if(surrenderBtn.disabled)return;stopTurnTimer();const winner=ai;gameOver=true;score[winner]++;matchScores[winner]++;stats.games++;stats.losses++;stats.streak=0;save();statusEl.textContent='Вы сдались.';render();if(matchScores[winner]>=targetWins()){matchFinished=true;showResult('Матч проигран','ИИ забирает матч.','🏳️')}else showResult('Раунд проигран','ИИ забирает раунд.','🏳️');beep(150,.25,'sawtooth')}
function syncPlayers(){human=mode==='ai'?playerMarkEl.value:'X';ai=human==='X'?'O':'X';save()}
function setMode(m){mode=m;syncPlayers();modeButtons.forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));difficultyWrap.hidden=mode!=='ai';markWrap.hidden=mode!=='ai';newMatch()}
modeButtons.forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));playerMarkEl.addEventListener('change',()=>{syncPlayers();newMatch()});
difficultyEl.addEventListener('change',()=>{save();statusEl.textContent='Сложность изменена';render()});matchLengthEl.addEventListener('change',()=>{save();newMatch()});starterEl.addEventListener('change',()=>{save();newMatch()});timeLimitEl.addEventListener('change',()=>{save();newMatch()});
soundToggle.addEventListener('click',()=>{soundOn=!soundOn;save();render();if(soundOn)beep(620,.08)});$('#restart').addEventListener('click',newMatch);undoBtn.addEventListener('click',undo);hintBtn.addEventListener('click',giveHint);surrenderBtn.addEventListener('click',surrender);
$('#resetScore').addEventListener('click',()=>{score={X:0,O:0};stats={games:0,wins:0,losses:0,draws:0,streak:0,perfect:0};save();newMatch()});
nextRoundBtn.addEventListener('click',()=>{if(matchFinished)newMatch();else startRound()});closeResultBtn.addEventListener('click',hideResult);resultModal.querySelector('[data-close-result]').addEventListener('click',hideResult);
document.addEventListener('keydown',e=>{if(!resultModal.hidden){if(e.key==='Enter')return nextRoundBtn.click();if(e.key==='Escape')return hideResult();return}if(e.key==='Escape'){newMatch();return}if(e.key.toLowerCase()==='z'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();undo();return}if(e.key.toLowerCase()==='h'){giveHint();return}const n=+e.key-1;if(n>=0&&n<9)move(n)});
modeButtons.forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));difficultyEl.value=localStorage.getItem('tttDifficulty')||'medium';matchLengthEl.value=localStorage.getItem('tttMatchLength')||'3';starterEl.value=localStorage.getItem('tttStarter')||'X';timeLimitEl.value=localStorage.getItem('tttTimeLimit')||'0';playerMarkEl.value=human;syncPlayers();difficultyWrap.hidden=mode!=='ai';markWrap.hidden=mode!=='ai';newMatch();
