(()=>{
const q=s=>document.querySelector(s),body=document.body,actions=q('.actions');if(!body||!actions)return;
const KEY='tttU100',get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}},set=(o)=>localStorage.setItem(KEY,JSON.stringify(o));
const state=get();const groups={
'Внешний вид':['Компактный интерфейс','Крупное поле','Мягкая подсветка','Сильная подсветка','Убрать тени','Высокий контраст','Монохром','Тёплый оттенок','Холодный оттенок','Стеклянная панель','Тонкие клетки','Круглые клетки','Большие символы','Маленькие символы','Скрыть вторичный текст','Убрать фоновой блеск','Плотные отступы','Воздушные отступы','Спокойные цвета','Яркие цвета'],
'Доступность':['Крупный текст','Увеличенный курсор','Яркий фокус','Подсветка хода','Подсветка пустых клеток','Не мигать','Минимум движения','Чёткие границы','Увеличить кнопки','Увеличить межстрочный интервал','Отключить blur','Постоянный статус','Подписывать клетки','Показывать номера 1–9','Упрощённый HUD','Не скрывать подсказки','Экранный режим без отвлечений','Фокус после хода','Фокус на модальном окне','Esc закрывает окна'],
'Игровой процесс':['Быстрый реванш','Автопереход раунда','Автоподсветка центра','Автоподсветка угрозы','Защита от двойного клика','Подтверждение сдачи','Подтверждение сброса','Блокировка настроек во время хода','Анимировать последний ход','Показывать последний ход','Счёт крупнее','Прогресс крупнее','Таймер крупнее','Мягкий таймаут','Звук победы','Звук поражения','Звук ничьей','Звук хода','Вибрация хода','Вибрация результата'],
'Статистика':['Процент побед','Лучшая серия','Победы за сегодня','Поражения за сегодня','Ничьи за сегодня','Средний результат','Последний результат','Всего матчей','Раунды за сессию','Время сессии','Победы Easy','Победы Medium','Победы Hard','Победы за неделю','Серия рекордов','История до 50 записей','Фильтр истории','Сводка матча','Сводка раунда','Рейтинг игрока'],
'Инструменты':['Копировать счёт','Копировать статус','Экспорт прогресса','Импорт прогресса','Случайная тема','Новый матч','Следующий раунд','Сбросить таймер сессии','Открыть историю','Открыть горячие клавиши','Полный экран','Выйти из полного экрана','Прокрутить к полю','Прокрутить к статистике','Проверка PWA','Проверка офлайн','Показать системную информацию','Очистить временные настройки','Синхронизировать вкладку','Показать версию Arena']};
const features=Object.entries(groups).flatMap(([g,n])=>n.map(name=>({group:g,name})));const names=Object.fromEntries(features.map((f,i)=>[`${i+1}`,f.name]));
const modal=document.createElement('div');modal.className='u100-modal';modal.hidden=true;modal.innerHTML='<div class="u100-backdrop"></div><section class="u100-dialog" role="dialog" aria-modal="true" aria-labelledby="u100Title"><header><div><span class="u100-kicker">ARENA LAB</span><h2 id="u100Title">100 улучшений</h2></div><button class="u100-close" type="button" data-close>✕</button></header><div class="u100-tools"><input id="u100Search" type="search" placeholder="Поиск улучшения…" aria-label="Поиск улучшения"><button id="u100All" type="button">Включить всё</button><button id="u100None" type="button">Выключить всё</button></div><div id="u100List" class="u100-list"></div><footer><span id="u100Count">0 / 100 включено</span><button class="u100-reset" id="u100Reset" type="button">Сбросить лабораторию</button></footer></section></div>';document.body.appendChild(modal);
const list=modal.querySelector('#u100List');
const cssMap=['u-compact','u-big-board','u-soft-glow','u-hard-glow','u-no-shadow','u-contrast','u-mono','u-warm','u-cool','u-glass','u-thin-cells','u-round-cells','u-big-symbols','u-small-symbols','u-hide-secondary','u-no-shine','u-tight','u-airy','u-calm','u-vivid','u-large-text','u-big-cursor','u-focus-strong','u-turn-glow','u-empty-glow','u-no-blink','u-low-motion','u-borders','u-big-buttons','u-line-height','u-no-blur','u-status-sticky','u-cell-labels','u-cell-nums','u-simple-hud','u-always-hints','u-distraction-free','u-focus-after','u-modal-focus','u-esc-close','u-fast-rematch','u-auto-round','u-center-hint','u-threat-hint','u-single-click','u-confirm-surrender','u-confirm-reset','u-lock-settings','u-last-animate','u-last-marker','u-big-score','u-big-progress','u-big-timer','u-soft-timeout'];
const classIds=new Set(cssMap.map((_,i)=>String(i+1)));
function count(){const n=Object.values(state).filter(Boolean).length;modal.querySelector('#u100Count').textContent=`${n} / 100 включено`}
function apply(){for(let i=0;i<100;i++)body.classList.toggle(`u100-${i+1}`,!!state[i+1]);cssMap.forEach((c,i)=>body.classList.toggle(c,!!state[i+1]));count();}
function action(i){const n=features[i-1]?.name||'';const click=s=>q(s)?.click();if(i===41)click('#restart');else if(i===42){if(localStorage.getItem('tttAuto')!=='on')localStorage.setItem('tttAuto','on');else click('#nextRound')}else if(i===43){click('#hintBtn')}else if(i===44){click('#hintBtn')}else if(i===45){click('#restart')}else if(i===46){const x=q('#surrenderBtn');if(x)click('#surrenderBtn')}else if(i===47){click('#resetScore')}else if(i===57){navigator.vibrate?.(25)}else if(i===58){navigator.vibrate?.(120)}else if(i===61){const t=q('#resultScore')?.textContent||`${q('#scoreX')?.textContent||0} : ${q('#scoreO')?.textContent||0}`;navigator.clipboard?.writeText(`KRESTIKI Arena — ${t}`)}else if(i===62){navigator.clipboard?.writeText(q('#status')?.textContent||'')}else if(i===63){q('button.history-button')?.click()}else if(i===64){q('input[type=file]')?.click()}else if(i===65){const t=q('#theme');if(t){const a=[...t.options].map(o=>o.value);t.value=a[Math.floor(Math.random()*a.length)];t.dispatchEvent(new Event('change'))}}else if(i===66)click('#restart');else if(i===67)click('#nextRound');else if(i===68){localStorage.setItem('tttSessionStart',String(Date.now()));location.reload()}else if(i===69)q('button.history-button')?.click();else if(i===70){alert('Горячие клавиши: 1–9 ход • стрелки навигация • Enter ход • Z отмена • H подсказка • F fullscreen • Esc новый матч.')}else if(i===71)click('#fullscreenToggle');else if(i===72){if(document.fullscreenElement)document.exitFullscreen?.()}else if(i===73)q('#board')?.scrollIntoView({behavior:'smooth',block:'center'});else if(i===74)q('.stats')?.scrollIntoView({behavior:'smooth',block:'center'});else if(i===75){alert('PWA: '+('serviceWorker' in navigator?'поддерживается':'не поддерживается'))}else if(i===76){alert(navigator.onLine?'Онлайн':'Офлайн')}else if(i===77){alert(`${navigator.platform} • ${navigator.language} • ${innerWidth}×${innerHeight}`)}else if(i===78){Object.keys(localStorage).filter(k=>k.startsWith('tttU100')).forEach(k=>localStorage.removeItem(k));alert('Временные настройки очищены')}else if(i===79){localStorage.setItem('tttSyncPing',String(Date.now()));alert('Синхронизация отмечена')}else if(i===80){alert('KRESTIKI Arena • Ultimate 100')}}
features.forEach((f,idx)=>{const i=idx+1,row=document.createElement('label');row.className='u100-item';row.dataset.name=f.name.toLowerCase();row.dataset.group=f.group;const input=document.createElement('input');input.type='checkbox';input.checked=!!state[i];const span=document.createElement('span');span.innerHTML=`<b>${i}. ${f.name}</b><small>${f.group}</small>`;row.append(input,span);input.addEventListener('change',()=>{state[i]=input.checked;set(state);apply();if(!classIds.has(String(i))&&input.checked)action(i)});list.appendChild(row)});
function filter(v){[...list.children].forEach(r=>r.hidden=!!v&&!r.dataset.name.includes(v)&&!r.dataset.group.toLowerCase().includes(v))}
modal.querySelector('#u100Search').addEventListener('input',e=>filter(e.target.value.toLowerCase()));modal.querySelector('#u100All').onclick=()=>{features.forEach((_,i)=>state[i+1]=true);set(state);[...list.querySelectorAll('input')].forEach(x=>x.checked=true);apply()};modal.querySelector('#u100None').onclick=()=>{features.forEach((_,i)=>state[i+1]=false);set(state);[...list.querySelectorAll('input')].forEach(x=>x.checked=false);apply()};modal.querySelector('#u100Reset').onclick=()=>{if(!confirm('Сбросить все 100 улучшений?'))return;Object.keys(state).forEach(k=>delete state[k]);set(state);[...list.querySelectorAll('input')].forEach(x=>x.checked=false);apply()};modal.addEventListener('click',e=>{if(e.target.matches('[data-close],.u100-backdrop'))modal.hidden=true});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)modal.hidden=true});
const open=document.createElement('button');open.type='button';open.className='u100-open';open.textContent='🧪 100 улучшений';actions.insertAdjacentElement('afterend',open);open.addEventListener('click',()=>{modal.hidden=false;modal.querySelector('#u100Search').focus()});
window.addEventListener('storage',()=>{Object.assign(state,get());apply()});apply();
})();