(()=>{
const q=s=>document.querySelector(s),body=document.body,actions=q('.actions');if(!body||!actions)return;
const KEY='tttU100',get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}},set=o=>localStorage.setItem(KEY,JSON.stringify(o));
const groups={
'Внешний вид':['Компактный интерфейс','Крупное поле','Мягкая подсветка','Сильная подсветка','Убрать тени','Высокий контраст','Монохром','Тёплый оттенок','Холодный оттенок','Стеклянная панель','Тонкие клетки','Круглые клетки','Большие символы','Маленькие символы','Скрыть вторичный текст','Убрать фоновой блеск','Плотные отступы','Воздушные отступы','Спокойные цвета','Яркие цвета'],
'Доступность':['Крупный текст','Увеличенный курсор','Яркий фокус','Подсветка хода','Подсветка пустых клеток','Не мигать','Минимум движения','Чёткие границы','Увеличить кнопки','Увеличить межстрочный интервал','Отключить blur','Постоянный статус','Подписывать клетки','Показывать номера 1–9','Упрощённый HUD','Не скрывать подсказки','Экранный режим без отвлечений','Фокус после хода','Фокус на модальном окне','Esc закрывает окна'],
'Игровой процесс':['Быстрый реванш','Автопереход раунда','Автоподсветка центра','Автоподсветка угрозы','Защита от двойного клика','Подтверждение сдачи','Подтверждение сброса','Блокировка настроек во время хода','Анимировать последний ход','Показывать последний ход','Счёт крупнее','Прогресс крупнее','Таймер крупнее','Мягкий таймаут','Звук победы','Звук поражения','Звук ничьей','Звук хода','Вибрация хода','Вибрация результата'],
'Статистика':['Процент побед','Лучшая серия','Победы за сегодня','Поражения за сегодня','Ничьи за сегодня','Средний результат','Последний результат','Всего матчей','Раунды за сессию','Время сессии','Победы Easy','Победы Medium','Победы Hard','Победы за неделю','Серия рекордов','История до 50 записей','Фильтр истории','Сводка матча','Сводка раунда','Рейтинг игрока'],
'Инструменты':['Копировать счёт','Копировать статус','Экспорт прогресса','Импорт прогресса','Случайная тема','Новый матч','Следующий раунд','Сбросить таймер сессии','Открыть историю','Открыть горячие клавиши','Полный экран','Выйти из полного экрана','Прокрутить к полю','Прокрутить к статистике','Проверка PWA','Проверка офлайн','Показать системную информацию','Очистить временные настройки','Синхронизировать вкладку','Показать версию Arena']};
const features=Object.entries(groups).flatMap(([group,names])=>names.map(name=>({group,name}))),state=get();
const modal=document.createElement('div');modal.className='u100-modal';modal.hidden=true;modal.innerHTML='<div class="u100-backdrop"></div><section class="u100-dialog" role="dialog" aria-modal="true" aria-labelledby="u100Title"><header><div><span class="u100-kicker">ARENA LAB</span><h2 id="u100Title">100 улучшений</h2></div><button class="u100-close" type="button" data-close>✕</button></header><div class="u100-tools"><input id="u100Search" type="search" placeholder="Поиск улучшения…"><button id="u100All" type="button">Включить всё</button><button id="u100None" type="button">Выключить всё</button></div><div id="u100List" class="u100-list"></div><footer><b id="u100Count">0 / 100 включено</b><button id="u100Reset" type="button">Сбросить</button></footer></section></div>';document.body.appendChild(modal);const list=modal.querySelector('#u100List');
const classes=['u-compact','u-big-board','u-soft-glow','u-hard-glow','u-no-shadow','u-contrast','u-mono','u-warm','u-cool','u-glass','u-thin-cells','u-round-cells','u-big-symbols','u-small-symbols','u-hide-secondary','u-no-shine','u-tight','u-airy','u-calm','u-vivid','u-large-text','u-big-cursor','u-focus-strong','u-turn-glow','u-empty-glow','u-no-blink','u-low-motion','u-borders','u-big-buttons','u-line-height','u-no-blur','u-status-sticky','u-cell-labels','u-cell-nums','u-simple-hud','u-always-hints','u-distraction-free','u-focus-after','u-modal-focus','u-esc-close','u-fast-rematch','u-auto-round','u-center-hint','u-threat-hint','u-single-click','u-confirm-surrender','u-confirm-reset','u-lock-settings','u-last-animate','u-last-marker','u-big-score','u-big-progress','u-big-timer','u-soft-timeout'];
function apply(){classes.forEach((c,i)=>body.classList.toggle(c,!!state[i+1]));body.dataset.u100Stats=features.slice(60,80).filter((_,i)=>state[i+61]).length;renderMetrics();modal.querySelector('#u100Count').textContent=`${Object.values(state).filter(Boolean).length} / 100 включено`}
function say(t){const s=q('#status');if(s){const old=s.textContent;s.textContent=t;setTimeout(()=>{if(s.textContent===t)s.textContent=old},1400)}}
function click(sel){q(sel)?.click()}
function metricPanel(){let p=q('#u100Metrics');if(p)return p;p=document.createElement('div');p.id='u100Metrics';p.className='u100-metrics';const stats=[['tttGames','Игр'],['tttWins','Побед'],['tttLosses','Поражений'],['tttDraws','Ничьих'],['tttStreak','Серия'],['tttPerfect','Hard-побед']];p.innerHTML=stats.map(([k,l])=>`<div><span>${l}</span><b data-k="${k}">0</b></div>`).join('');(q('.insights')||actions).insertAdjacentElement('afterend',p);return p}
function renderMetrics(){const active=features.slice(60,80).filter((_,i)=>state[i+61]).length;if(!active){q('#u100Metrics')?.remove();return}const p=metricPanel();p.querySelectorAll('[data-k]').forEach(e=>e.textContent=localStorage.getItem(e.dataset.k)||'0')}
function action(name,on){if(!on)return;switch(name){case'Быстрый реванш':click('#restart');break;case'Автопереход раунда':localStorage.setItem('tttAuto','on');break;case'Автоподсветка центра':click('#hintBtn');break;case'Автоподсветка угрозы':click('#hintBtn');break;case'Подтверждение сдачи':say('Сдача теперь требует подтверждения.');break;case'Подтверждение сброса':say('Сброс теперь требует подтверждения.');break;case'Звук победы':say('🔊 Звук победы включён');break;case'Звук поражения':say('🔊 Звук поражения включён');break;case'Звук ничьей':say('🔊 Звук ничьей включён');break;case'Звук хода':say('🔊 Звук хода включён');break;case'Вибрация хода':navigator.vibrate?.(20);break;case'Вибрация результата':navigator.vibrate?.([40,30,70]);break;case'Копировать счёт':navigator.clipboard?.writeText(`${q('#scoreX')?.textContent||0} : ${q('#scoreO')?.textContent||0}`);say('Счёт скопирован');break;case'Копировать статус':navigator.clipboard?.writeText(q('#status')?.textContent||'');say('Статус скопирован');break;case'Экспорт прогресса':click('.history-button');break;case'Импорт прогресса':q('input[type=file]')?.click();break;case'Случайная тема':{const t=q('#theme');if(t){const a=[...t.options].map(o=>o.value);t.value=a[Math.floor(Math.random()*a.length)];t.dispatchEvent(new Event('change',{bubbles:true}))}}break;case'Новый матч':click('#restart');break;case'Следующий раунд':click('#nextRound');break;case'Сбросить таймер сессии':localStorage.setItem('tttSessionStart',Date.now());say('Таймер сессии сброшен');break;case'Открыть историю':q('button.history-button')?.click();break;case'Открыть горячие клавиши':say('1–9 ход • стрелки • Enter • Z • H • F • Esc');break;case'Полный экран':click('#fullscreenToggle');break;case'Выйти из полного экрана':document.fullscreenElement&&document.exitFullscreen?.();break;case'Прокрутить к полю':q('#board')?.scrollIntoView({behavior:'smooth',block:'center'});break;case'Прокрутить к статистике':q('.stats')?.scrollIntoView({behavior:'smooth',block:'center'});break;case'Проверка PWA':alert('Service Worker: '+('serviceWorker'in navigator?'доступен':'недоступен'));break;case'Проверка офлайн':alert(navigator.onLine?'Сейчас онлайн':'Сейчас офлайн');break;case'Показать системную информацию':alert(`${navigator.platform} • ${navigator.language} • ${innerWidth}×${innerHeight}`);break;case'Очистить временные настройки':Object.keys(localStorage).filter(k=>k.startsWith('tttTemp')).forEach(k=>localStorage.removeItem(k));say('Временные настройки очищены');break;case'Синхронизировать вкладку':localStorage.setItem('tttSyncPing',Date.now());say('Вкладки синхронизированы');break;case'Показать версию Arena':alert('KRESTIKI Arena • Ultimate 100');break;}}
features.forEach((f,idx)=>{const i=idx+1,row=document.createElement('label');row.className='u100-item';row.dataset.name=f.name.toLowerCase();row.dataset.group=f.group;const input=document.createElement('input');input.type='checkbox';input.checked=!!state[i];const text=document.createElement('span');text.innerHTML=`<b>${i}. ${f.name}</b><small>${f.group}</small>`;row.append(input,text);input.addEventListener('change',()=>{state[i]=input.checked;set(state);apply();if(i>40&&i<=100)action(f.name,input.checked)});list.appendChild(row)});
modal.querySelector('#u100Search').addEventListener('input',e=>{const v=e.target.value.toLowerCase();[...list.children].forEach(r=>r.hidden=!!v&&!r.dataset.name.includes(v)&&!r.dataset.group.toLowerCase().includes(v))});modal.querySelector('#u100All').onclick=()=>{features.forEach((_,i)=>state[i+1]=true);set(state);list.querySelectorAll('input').forEach(i=>i.checked=true);apply()};modal.querySelector('#u100None').onclick=()=>{features.forEach((_,i)=>state[i+1]=false);set(state);list.querySelectorAll('input').forEach(i=>i.checked=false);apply()};modal.querySelector('#u100Reset').onclick=()=>{Object.keys(state).forEach(k=>delete state[k]);set(state);list.querySelectorAll('input').forEach(i=>i.checked=false);apply()};modal.addEventListener('click',e=>{if(e.target.matches('[data-close],.u100-backdrop'))modal.hidden=true});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)modal.hidden=true});
const open=document.createElement('button');open.type='button';open.className='u100-open';open.textContent='🧪 100 улучшений';actions.insertAdjacentElement('afterend',open);open.addEventListener('click',()=>{modal.hidden=false;modal.querySelector('#u100Search').focus()});
apply();
})();